### PR TITLE
(fix) implement market order check at exchange level

### PR DESCRIPTION
**Pull request by mark-antony1**
- targets Issue #43 
- moves market order check to exchange sub-class
@nasaWelder

### CODE REVIEW

**Comment by needmoney90** [comment]
I think it would be better to have a flag on the exchange object for whether it can make market orders or not (default to false). Then, the exchange object checks for the flag. If the market order flag is false, then the exchange object checks the top of the orderbook, and places the order if it wont make a market order.

**Comment by needmoney90** [comment]
That should get rid of the race condition

**Comment by nasaWelder** [comment]
I was thinking buy/sell would grab order book itself. So it doesn't need another arg from caller

**Comment by needmoney90** [comment]
Yeah, my suggestion is to have the exchange object check the orderbook, check the flag, and then place the order (and retry all those steps if it fails). The buy/sell functions on the exchange interfaces shouldnt do the decision if theres a market order.

**Comment by needmoney90** [comment]
I just stubbed out how I think it should look, I need to go to a thing tonight, so I don't have time to actually code in the logic right this second. I'll get to it in a couple hours, unless one of you wants to do it. I'll close this PR once the logic is in the Exchange class (and not the interfaces).

https://github.com/livinginformation/merkato/blob/master/merkato/exchanges/exchange.py#L23
https://github.com/livinginformation/merkato/blob/master/merkato/exchanges/exchange.py#L36

**Comment by nasaWelder** [comment]
... but some interfaces allow limit only as part of API call

**Comment by needmoney90** [comment]
Let me think on this.

**Comment by nasaWelder** [comment]
https://www.kraken.com/help/api#private-user-trading
ordertype = order type:
    market
    limit (price = limit price)
    stop-loss (price = stop loss price)
    take-profit (price = take profit price)
    stop-loss-profit (price = stop loss price, price2 = take profit price)
    stop-loss-profit-limit (price = stop loss price, price2 = take profit price)
    stop-loss-limit (price = stop loss trigger price, price2 = triggered limit price)
    take-profit-limit (price = take profit trigger price, price2 = triggered limit price)
    trailing-stop (price = trailing stop offset)
    trailing-stop-limit (price = trailing stop offset, price2 = triggered limit offset)
    stop-loss-and-limit (price = stop loss price, price2 = limit price)
    settle-position

**Comment by needmoney90** [comment]
Lets add limit_only as a param on the buy/sell exchange interfaces, so we can treat all exchanges as if that was a param (and implement that functionality in the interfaces for those exchanges that are missing it)

**Comment by mark-antony1** [comment]
Commented on the stub out, We should rethink how we go about OOP. 

It might be better to have an exchange interface that all specific exchanges use. In this case the merkato object would access the exchange directly.

**Pull request closed without merging**
