### PR TITLE
(fix) update readme with installation and test parameters, update tes…

### PR DESCRIPTION
**Pull request by mark-antony1**
-update readme with installation
-update tests for new OOP structure
**GET APPROVAL FROM @evdc BEFORE MERGING AS THIS CHANGES HIS TEST SUITE**

### CODE REVIEW

**Comment by needmoney90** [comment]
@evdc waiting on your approval for a merge.

**Comment by needmoney90** [comment]
Modified it to use config everywhere, uniform variable syntax.

**Comment by evdc** [comment]
Where is the retry logic, etc. from the Exchange class moved to? is it now in `TuxExchange` or `Merkato`? Wherever it is, the tests for it (in `test_exchange.py`commented out) should probably be migrated appropriately. 

👍 on using config everywhere and uniform syntax

**Comment by nasaWelder** [comment]
If we're using config everywhere, can I get a comment at the top of merkato object that details the full tree of required key:values in that dictionary? I need to know how to kick off a merkato instance without hunting through the code.

**Comment by mark-antony1** [comment]
@evdc the retry logic is based in the exchange.py file of the tux_exchange directory. The test_exchange file has been commented out entirely as we do not currently use the exchange class in the exchanges directory in this implementation.

**Comment by evdc** [comment]
ok, so can we move testing retry logic etc. to the appropriate place, which sounds like it would be `test_tux_exchange.py`, and then delete `test_exchange.py` as it's no longer needed?

Also will the same retry logic be reproduced in the other exchange interfaces then?

**Comment by mark-antony1** [comment]
Yes, the same logic would need to be replicated. There is a tradeoff off duplicate code.

**Comment by mark-antony1** [comment]
@evdc @livinginformation Any additional changes needed?

**Comment by needmoney90** [comment]
No suggestions from me (if the exchange.py is being removed). The commented out code has configuration instead of config, but if its deprecated, we're fine.

**Comment by needmoney90** [comment]
Once @evdc gives the ok, I'll merge.

**Review by evdc — APPROVED** [review]
sorry I'm slow at responding! approved.

**Comment by needmoney90** [comment]
Merged, thanks!

**Pull request merged**
