### PR TITLE
(fix) merkato init params to match db

### PR DESCRIPTION
**Pull request by mark-antony1**

### CODE REVIEW

**Review by needmoney90 — APPROVED** [review]

**Comment by nasaWelder** [comment]
Breaks simple app, we need to be careful about changing stuff that affects intra application api.

**Comment by nasaWelder** [comment]
And db init script probably

**Comment by 15chrjef** [comment]
Simple app runs fine, steps to reproduce?

**Comment by nasaWelder** [comment]
Make a new test Exchange merkato. It uses the old merkato argument names, so does db init script.

**Pull request merged**
