### PR TITLE
More logging

### PR DESCRIPTION
**Pull request by evdc**
Add logging to merkato.py and minor cleanup

Addresses #230

### CODE REVIEW

**Review by needmoney90 — COMMENTED** [review]
Can you add a log message (debug) at the head of every function saying that it was entered?

**Comment by mark-antony1** [comment]
That could get very verbose @livinginformation

**Comment by needmoney90** [comment]
Just talking about merkato.py, shouldn't be too much of an issue

**Comment by mark-antony1** [comment]
ok

**Comment by evdc** [comment]
@livinginformation added it

**Pull request merged**
