### PR TITLE
(fix) GUI to incorporate binance data

### PR DESCRIPTION
**Pull request by mark-antony1**

### CODE REVIEW

**Comment by nasaWelder** [comment]
I'm ok with the first change, ignoring if extra data. Adding switch case for exchange is tech debt if there's ever a new interface. This should be handled at exchange.py not here.

**Comment by mark-antony1** [comment]
Its not tech debt, if we have many exchanges with different interfaces we would have a switch statement and extract it.

**Comment by nasaWelder** [comment]
Context should be a sacred API. Put the translation in merkato, or better at exchange.py level

**Comment by nasaWelder** [comment]
You're not thinking 4th dimensionally. Where we're going, we won't need simply app

**Comment by mark-antony1** [comment]
I am thinking about each and every part of this

**Comment by mark-antony1** [comment]
I understand your intentions around context, the number of transactions that would need to be processed is quite large and could be infinitely large, this format will work without issue, we can change in the future as necessary.

**Comment by needmoney90** [comment]
I agree with @nasaWelder here. The GUI code should be fairly devoid of logic. The data should come in a specified formatting within the context, and then be rendered according to that specification by whatever front-end we decide to plug it into. I think that's a reasonable separation of concerns.

**Comment by nasaWelder** [comment]
Gui doesn't need all open orders just highest/lowest bid/ask. That would reduce computation if new functionss were made at exchange level to provide those.

**Comment by mark-antony1** [comment]
You would still need to sort for them both

**Comment by nasaWelder** [comment]
Yes, but sort them in their native format. Prevents double iteration/translation

**Review by needmoney90 — APPROVED** [review]

**Pull request merged**
