### PR TITLE
Update exchange.py

### PR DESCRIPTION
**Pull request by needmoney90**

### CODE REVIEW

**Review by mark-antony1 — COMMENTED** [review]
sort the list by order ID prior to returning it.

**Comment by needmoney90** [comment]
We actually want to sort by the order price, after thinking.

**Comment by mark-antony1** [comment]
why?

**Comment by nasaWelder** [comment]
I'm going to sort it explicitly with the GUI regardless...

**Comment by needmoney90** [comment]
@15chrjef this is our open orders, so displaying it in ascending or descending order of price is canonical

**Review by mark-antony1 — APPROVED** [review]

**Review by nasaWelder — APPROVED** [review]

**Pull request merged**
