### PR TITLE
(fix) step and methods for buy/sell

### PR DESCRIPTION
**Pull request by mark-antony1**

### CODE REVIEW

**Comment by nasaWelder** [comment]
Why drastic change in step? Just curious.

**Comment by needmoney90** [comment]
I believe its because I suggested there might be a min order size, and he wanted to make sure orders were large enough. Seems excessive though, and I need to code it to be dynamic.

**Comment by mark-antony1** [comment]
This is for testing purposes. We will change as appropriate but @livinginformation needs this to figure out the bids

**Comment by nasaWelder** [comment]
Other exchanges post their minimum order size, should make it a constant.

**Comment by needmoney90** [comment]
thats the plan, nasa

**Comment by mark-antony1** [comment]
All set @livinginformation @nasaWelder ?

**Pull request merged**
