### PR TITLE
(feature) update last order in sqlite when placing buy/sell orders

### PR DESCRIPTION
**Pull request by mark-antony1**

### CODE REVIEW

**Comment by nasaWelder** [comment]
This might not be the place, but I really think the exchange instance should know it's own ticker. It should be a part of instantiation.

**Comment by needmoney90** [comment]
Logically it belongs in the Merkato instance (the pair is really part of the merkato, not the exchange interface), but in terms of DRY logic, sticking it in Exchange makes the most sense. I'm in favor of that.

**Review by needmoney90 — APPROVED** [review]

**Comment by mark-antony1** [comment]
Then the merkato class would have to get the ticker by accessing the exchange. Thats could work, but i am worries about the seperation of concerns that it violates.

**Comment by nasaWelder** [comment]
I'll work on a PR that might convince yall, tonight. Tldr the merkato doesn't know the exchange specific ticker anyways without asking.

**Pull request merged**
