### PR TITLE
(feature) implement basic test exchange

### PR DESCRIPTION
**Pull request by mark-antony1**

### CODE REVIEW

**Comment by nasaWelder** [comment]
1. How does market price fluctuate? (I use a random number generator for fake merkato in simple app) 

2. what is the purpose of user ID?

3. Can coin pair and starting price be set on instantiation?

**Comment by needmoney90** [comment]
We can either implement price movement as a random walk, or set up a predetermined series of market buys/sells (with amounts). I'm leaning towards the second (and we can probably do a random generation of the amounts later). 

Edit: note that the random walk would just sell or buy as much as necessary to reach the generated price.

**Comment by needmoney90** [comment]
For 2, im assuming @15chrjef wants this exchange to be able to have multiple merkatos active on it at once (different users).

**Comment by nasaWelder** [comment]
That doesn't make sense though, each exchange object is per merkato, if you were running two of the same bot that's a violation anyways

**Comment by needmoney90** [comment]
This is a bit different, in this case we aren't wrapping exchange requests, we're actually implementing exchange functions.

**Comment by nasaWelder** [comment]
If you continue on that path, you've made an actual exchange. (Which is cool) but Since our other exchange objects are just gateway to outside world, just make it lie to us and fake the action itself

**Comment by mark-antony1** [comment]
@livinginformation  This exchange was not intended to have multiple active markets on it, but feel free to implement it as such.

My intention was to have one merkato use the test exchange with some fake data set up, which someone needs to implement, and then generate 'random' trades also needs to be implemented.

@nasaWelder  the ID is for tracking the account balances within the exchange, i don't know if we need this or not, but it might help calculate profit.

**Comment by needmoney90** [comment]
I'll defer to @15chrjef to explain this for now, @nasawelder I'll merge when you're satisfied.

**Comment by needmoney90** [comment]
@15chrjef your use of the ID was the reason for me assuming there would be multiple users. I'll merge this for now, under the assumption that the spec for the exchange isn't nailed down yet. We'll chat about it later today if you're free.

**Pull request merged**
