### PR TITLE
fix some loose ends in conversion to classes. loose ends remain (with…

### PR DESCRIPTION
**Pull request by nasaWelder**
… comments)

### CODE REVIEW

**Review by nasaWelder — COMMENTED** [review]
Need to fix line 43 in exchange.py.... doh

**Comment by needmoney90** [comment]
@nasaWelder merged, where's the issue in line 43? Line 60 has it as well if so, right?

**Comment by needmoney90** [comment]
haven't caught up on the new debug syntax, i'll take a look

**Comment by nasaWelder** [comment]
Syntax error line 43. The extra quoteon front of  word ""ERROR"

**Comment by needmoney90** [comment]
Fixed

**Pull request merged**
